version: '3'
services:
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
    restart: "no"
  php:
    image: php:7.4-cli
    restart: "no"
    volumes:
      - .:/app
    working_dir: /app
